export enum UserRoleEnum {
  CLIENT = 'CLIENT',
  DRIVER = 'DRIVER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  WILAYA_MANAGER = 'WILAYA_MANAGER',
  COMMUNE_MANAGER = 'COMMUNE_MANAGER',
  AGENT = 'AGENT',
}
